# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 https://sauber92.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /hydejack

title:               sauber92's Blog

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Hello I'm sauber92.  

  sauber92의 블로그입니다.

# The tags listed as entries in the sidebar
sidebar_tags:        [Project, Study, Review]

# Fallback image and color if not overwritten for tag or post
image:               /hydejack/public/img/nap.jpg
color:               '#A85641'

# Fonts
font:                '"Nanum Gothic", "PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Junyoung Jung'

  # This photo will be used in the about section
  photo:             https://scontent-hkg3-1.xx.fbcdn.net/v/t1.0-1/p320x320/13237805_968492259936062_3366953170761019237_n.jpg?oh=2ac19ea625d2c85516b989447f3e1af3&oe=58C175E0 
#  photo2x:           @2x.jpeg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    안녕하세요, 저는 임베디드와 웹에 관심이 있는 [정준영](https://www.linkedin.com/in/junyoung-jung-4a9459130)([@sauber92](https://github.com/sauber92))입니다.

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    github:          sauber92
    facebook:        profile.php?id=100003258917365
    instagram:       jjy920517
    linkedin:        junyoung-jung-4a9459130
    youtube:         UCa6FuXaNhEZxwyilY9FPWCg
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # github:          _username_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-88344613-1'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
